### ISSUE TITLE
Deep setting?

### ISSUE THREAD

**Issue by siddharthkp** [remy/undefsafe#8]
```js
let object = {};
undefsafe(object, 'a.b', 10);
```

creates an object which is
```js
{ b: 10 }
```

instead of 
```js
{ a: { b: 10 } }
```

Similarly,
```js
undefsafe(object, 'a.b.c', 10) // is { c: 10 }
```

Am I missing something?

**Comment by remy** [comment]
You are :) 

undefsafe returns the property in question, it doesn't filter down to the matched property (which I think is what you're expecting).

**Comment by siddharthkp** [comment]
Makes sense while fetching, but not so much while setting :(

**Comment by remy** [comment]
Can you draw up an example case? Really the setting is to provide a fallback value, rather than modifying the object (some ala `{ ...obj, change }`).

**Comment by siddharthkp** [comment]
> safely set deep values
Hmm, I guess `safely` makes all the difference. I get it.

For what's it worth, my use case was copying fields from an object based on a whitelist.

```js
let whitelist = ['data.name', 'data.username']

let user = {
   name: 'siddharth',
   username: 'siddharthkp',
   address: 'dont-copy-me-bro'
}

let object = {}

for (let field in whitelist) undefsafe(object, field, undefsafe(user, field))
```
