### ISSUE TITLE
Register in Bower.

### ISSUE THREAD

**Issue by sanjmara** [remy/undefsafe#9]
I found this is a very useful library and included in our product. Thanks!
Why don't we register this in Bower also in order to support client side?

**Comment by remy** [comment]
It already works client side. I'm guessing you mean so you can install it
via your preferred method?

What's involved in registering in bower? I don't use it, so I'm not
familiar with how it works.

**Comment by sanjmara** [comment]
Thanks for the quick response! Bower is for client side package repository and it is widely used. It is similar to npm.
I can still use npm for client side but this library is worth having in bower as well.
It is simple! Check this
https://bower.io/docs/creating-packages/#register
